export default {
    user: null,
    products: [],
    categories: [],
    shippings: [],
    payments: [],
    events: [],
    cart: [],
    themes: [],
    address: {},
    fav: [],
    orders: [],
    general: {},
    variations: [],
    activeIndex: 1,
    lang: 'en',
    isPageReady: false,
    cartTotal: 0,
    cartLength: 0,
    hasProducts: true,
}